# Generated by Django 2.1.8 on 2019-04-16 17:34

import annoying.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0010_memberbalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='CCCBProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_keyholder', models.BooleanField(default=False)),
                ('member', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cccb_profile', to='members.Member')),
            ],
        ),
    ]
